### ISSUE TITLE
Errors for code in HANA

### ISSUE THREAD

**Issue by DaveRUK** [saphanaacademy/xsaJobsXSJS#1]
HI,

have copied this code into my project but am getting an error as shown below

![image](https://user-images.githubusercontent.com/38691656/39186068-2a669b2c-47c1-11e8-8981-a3807ec6ba4b.png)

Can't see any difference between the code provided and that which I have copied, but new to JS in the hana environments

Code has been copied from 

![image](https://user-images.githubusercontent.com/38691656/39187806-223f2522-47c6-11e8-8423-62e3673bc9d1.png)

Any help or suggestions gratefully appreciated

**Comment by saphanaacademy** [comment]
Hi,
Sounds like whitespace or tab or incorrect double quotes causing the issue after copy/paste.
Can you try pasting the code into a text editor like Notepad++ where you can choose to view all symbols / characters such as tab, crlf, quotes, other special characters etc? Hopefully whatever character is causing the issue will become obvious...
Philip

**Comment by DaveRUK** [comment]
Thanks for the prompt response Philip

Can only see tabs and CR

![image](https://user-images.githubusercontent.com/38691656/39188210-1cc54936-47c7-11e8-97fc-2cdba224d278.png)

Have tried removing all but still the same issue

Any other ideas?

![image](https://user-images.githubusercontent.com/38691656/39188291-58dcc958-47c7-11e8-8f86-1f762c15b154.png)

**Comment by saphanaacademy** [comment]
Hmmmm... very strange. Unable to reproduce this myself. 

Maybe try one of the following:
- Remove line 2 and see what happens - does the error go away or simply move somewhere else?
- Manually replace the double quote and/or colon & space characters

Which HANA SPS are you using and which type (HANA Express, on-premise etc.)?

Philip

**Comment by DaveRUK** [comment]
Thanks again Philip

have manually replace all colons, spaces and quotes - same error

Have removed line 2 and the error moves to the next line down

Using on hana on prem - 2.0 SPS02

**Comment by saphanaacademy** [comment]
Try renaming the file to myJob.xsjob 😉

**Comment by DaveRUK** [comment]
Yay - thanks very much for your patience and help...still getting to grips with coding required :)
